### ISSUE TITLE
one-liner-instances-0.1.3.0 fails to build with ghc-9.12.2

### ISSUE THREAD

**Issue by juhp** [mstksg/one-liner-instances#2]
Reporting for the Stackage team:

```
       /home/curators/work/unpack-dir/unpacked/one-liner-instances-0.1.3.0-af3468c83e7142e6f71260f39884ba0ed8c70e89a1aa5f3e986190717
f806bb2/src/System/Random/Stateful/OneLiner.hs:88:10: error: [GHC-39999]
           • Could not deduce ‘UniformRange a’                                                                                      
               arising from a use of ‘System.Random.Internal.$dmisInRange’                                                          
             from the context: (ADTRecord a, Constraints a UniformRange)
               bound by the instance declaration                                                                                    
               at src/System/Random/Stateful/OneLiner.hs:(88,10)-(91,34)                                                            
             Possible fix:                                                                                                          
               add (UniformRange a) to the context of the instance declaration                                                      
           • In the expression:                                                                                                     
               System.Random.Internal.$dmisInRange @(GUniform a)  
             In an equation for ‘isInRange’:                                                                                        
                 isInRange = System.Random.Internal.$dmisInRange @(GUniform a)                                                      
             In the instance declaration for ‘UniformRange (GUniform a)’                                                            
          |                                                                                                                         
       88 | instance ( ADTRecord a                                                                                                  
          |          ^^^^^^^^^^^^^...                             
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/one-liner-instances-0.1.3.0-af3468c83e7142e6f71260f39884ba0ed8c70e89a1aa5f3e986190717
f806bb2/src/System/Random/Stateful/OneLiner.hs:155:10: error: [GHC-39999]
           • Could not deduce ‘UniformRange a’                    
               arising from a use of ‘System.Random.Internal.$dmisInRange’                                                          
             from the context: (ADT a, Constraints a UniformRange) 
               bound by the instance declaration                                                                                    
               at src/System/Random/Stateful/OneLiner.hs:(155,10)-(158,37)
             Possible fix:
               add (UniformRange a) to the context of the instance declaration
           • In the expression:
               System.Random.Internal.$dmisInRange @(GUniformSum a)
             In an equation for ‘isInRange’:
                 isInRange = System.Random.Internal.$dmisInRange @(GUniformSum a)
             In the instance declaration for ‘UniformRange (GUniformSum a)’
           |
       155 | instance ( ADT a
           |          ^^^^^^^...
```

**Comment by andreasabel** [comment]
Indeed this is still the case. 
@mstksg maybe you have not seen this.  The minimal fix would be to make hackage revisions that prevent bad dependency selections.

The culprit seems to be `random-1.3` rather than GHC 9.12.  `cabal build -c 'random<1.3'` works.
I made a revision on hackage:

Pushing "one-liner-instances-0.1.3.0.cabal" (one-liner-instances-0.1.3.0~1) ...

Changes in this revision:

<ul>
  
 * Changed the library component&#39;s library dependency on &#39;random&#39;
                          from `>=1.2`
                          to `>=1.2 && <1.3`

</ul>

**Comment by andreasabel** [comment]
`one-liner-instances` dropped out of Stackage nightly because of the `random-1.3` compatibility issue.  Would be great to have it back in Stackage!

**Comment by mstksg** [comment]
hi @andreasabel, thanks for letting me know. I feel like now that Generically has been in base for years now I should probably just retire this package anyway 😅
